# Netlify configuration file

[build]
  publish = "./"
  command = "# no build command needed for static site"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"